[services.api]
build = "server"
depends_on = ["db"]
expose = ["5000"]
volumes = ["./server:/program"]

[services.client]
build = "client"
expose = ["5173"]
volumes = ["./client:/program"]

[services.db]
build = { context = ".", dockerfile = "db.Dockerfile" }
expose = ["5432"]

[services.haproxy]
build = { context = ".", dockerfile = "haproxy.Dockerfile" }
depends_on = ["api", "client"]
ports = ["8000:8000"]
