services:
    api:
        build: server
        depends_on:
            - db
        ports:
            - "5000"
        volumes:
            - ./server:/program
    db:
        build:
            context: .
            dockerfile: db.Dockerfile
        expose:
            - "5432"
