[client]
origin = "http://kotori.lab:55555"

[cookie]
path = "/"
same_site = "Lax"
secure = false

[csrf]
token_bits = 256
cookie = "csrf_token"
cookie_lifetime = 31_104_000
header = "CSRF-Token"
response_field = "csrf_token"

[db]
dbname = "(replaced by test name)"
application_name = "(replaced by test name)"
user = "(replaced by test name)"
password = "dodatok"
host = "db"
port = 5432

[dev]
debug = true
testing = true

[dev.init_db]
dbname = "postgres"
application_name = "(replaced by test name)"
user = "postgres"
password = "pw"
host = "db"
port = 5432

[redis]
url = "unix:///run/redis/redis.sock?db=0"
key_separator = "|"

[remember_token]
cookie = "remember_token"
cookie_lifetime = 31_104_000
id_bits = 256
secret_bits = 256
separator = "."

[security]
aes_key = "87428fc522803d31065e7bce3cf03fe475096631e5e07bbd7a0fde60c4cf25c7"
argon2_memory_cost = 65536
argon2_time_cost = 3
argon2_parallelism = 4
password_salt_bits = 128

[session]
cookie = "session"
id_bits = 256
lifetime = 31_104_000
sudo_lifetime = 86_400

[totp]
algorithm = "SHA-1"
digits = 6
key_length = 40
time_step = 30
time_window = 1

[user]
id_bits = 256
icon_id_bits = 256
username_min_length = 1
username_max_length = 32
password_min_length = 8
password_max_length = 1000

[websocket]
channel_capacity = 32
connection_id_bits = 256
token_bits = 256
token_lifetime = 60
